[package]
name = "seseragi-ssr-demo-client"
version = "0.1.0"
language = ">=0.1.0 <0.2.0"

[run]
entry = "main"
target = "web"

[dependencies]
ui = { package = "seseragi-ssr-demo-ui", path = "../ui" }
