FROM oven/bun:1

WORKDIR /app

COPY generated ./generated
COPY vercel-node-modules ./generated/node_modules
COPY client-dist ./client-dist
COPY container ./container

ENV NODE_ENV=production

CMD ["bun", "container/entry.ts"]
